/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package rs.ac.bg.fon.ai.zajednicki.komunikacija;

import java.io.Serializable;

/**
 *
 * @author milos
 */
public enum Operacija implements Serializable {
    LOGIN, ODJAVI_FIZIJATRA, 
    UCITAJ_TERAPIJE, OBRISI_TERAPIJU, DODAJ_TERAPIJU, IZMENI_TERAPIJU,
    UCITAJ_TIPOVE_PACIJENATA, OBRISI_TIP_PACIJENTA, DODAJ_TIP_PACIJENTA, IZMENI_TIP_PACIJENTA,
    UCITAJ_SPECIJALIZACIJE, OBRISI_SPECIJALIZACIJU, DODAJ_SPECIJALIZACIJU, IZMENI_SPECIJALIZACIJU, 
    UCITAJ_FIZIJATRE, OBRISI_FIZIJATRA, DODAJ_FIZIJATRA, IZMENI_FIZIJATRA,
    UCITAJ_NALAZE, OBRISI_NALAZ, DODAJ_NALAZ, IZMENI_NALAZ,  
    UCITAJ_STAVKE_NALAZA, OBRISI_STAVKU_NALAZA, DODAJ_STAVKU_NALAZA, IZMENI_STAVKU_NALAZA,UCITAJ_SVE_STAVKE_NALAZA,
    AZURIRAJ_CENU_NALAZA, 
    UCITAJ_PACIJENTE, OBRISI_PACIJENTA, DODAJ_PACIJENTA, IZMENI_PACIJENTA,
    DODAJ_FIZIJATRA_SPECIJALIZACIJU, OBRISI_FIZIJATRA_SPECIJALIZACIJU, 
    
    
}
