/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ai.klijent.forme;

import rs.ac.bg.fon.ai.zajednicki.domen.Terapija;
import rs.ac.bg.fon.ai.zajednicki.domen.Fizijatar;
import rs.ac.bg.fon.ai.zajednicki.domen.Pacijent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import rs.ac.bg.fon.ai.klijent.niti.DodavanjeStavkeNalazaNit;

/**
 *
 * @author milos
 */
public class DodajNalazForma extends javax.swing.JFrame {

    private DodavanjeStavkeNalazaNit nit;
    /**
     * Creates new form DodajNalazForma
     */
    public DodajNalazForma() {
        initComponents();
    }

    public JButton getjButtonObrisiStavku() {
        return jButtonObrisiStavku;
    }

    public void setjButtonObrisiStavku(JButton jButtonObrisiStavku) {
        this.jButtonObrisiStavku = jButtonObrisiStavku;
    }


    
    public JButton getjButtonDodajStavku() {
        return jButtonDodajStavku;
    }

    public void setjButtonDodajStavku(JButton jButtonDodajStavku) {
        this.jButtonDodajStavku = jButtonDodajStavku;
    }

    public JButton getjButtonIzmeniNalaz() {
        return jButtonIzmeniNalaz;
    }

    public void setjButtonIzmeniNalaz(JButton jButtonIzmeniNalaz) {
        this.jButtonIzmeniNalaz = jButtonIzmeniNalaz;
    }

    public JButton getjButtonIzmeniStavku() {
        return jButtonIzmeniStavku;
    }

    public void setjButtonIzmeniStavku(JButton jButtonIzmeniStavku) {
        this.jButtonIzmeniStavku = jButtonIzmeniStavku;
    }

    public JComboBox<Terapija> getjComboBoxSveTerapije() {
        return jComboBoxSveTerapije;
    }

    public void setjComboBoxSveTerapije(JComboBox<Terapija> jComboBoxSveTerapije) {
        this.jComboBoxSveTerapije = jComboBoxSveTerapije;
    }

    public JTextField getjTextFieldCenaTerapije() {
        return jTextFieldCenaTerapije;
    }

    public void setjTextFieldCenaTerapije(JTextField jTextFieldCenaTerapije) {
        this.jTextFieldCenaTerapije = jTextFieldCenaTerapije;
    }

    
    public JButton getjButtonDodajNalaz() {
        return jButtonDodajNalaz;
    }

    public void setjButtonDodajNalaz(JButton jButtonDodaj) {
        this.jButtonDodajNalaz = jButtonDodaj;
    }

    

    public JTextField getjTextFieldDatum() {
        return jTextFieldDatum;
    }

    public void setjTextFieldDatum(JTextField jTextFieldDatum) {
        this.jTextFieldDatum = jTextFieldDatum;
    }

    

    public JTextField getjTextFieldOpis() {
        return jTextFieldOpis;
    }

    public void setjTextFieldOpis(JTextField jTextFieldOpis) {
        this.jTextFieldOpis = jTextFieldOpis;
    }

    public JComboBox<Fizijatar> getjComboBoxFizijatar() {
        return jComboBoxFizijatar;
    }

    public void setjComboBoxFizijatar(JComboBox<Fizijatar> jComboBoxFizijatar) {
        this.jComboBoxFizijatar = jComboBoxFizijatar;
    }

    public JComboBox<Pacijent> getjComboBoxPacijent() {
        return jComboBoxPacijent;
    }

    public void setjComboBoxPacijent(JComboBox<Pacijent> jComboBoxPacijent) {
        this.jComboBoxPacijent = jComboBoxPacijent;
    }

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldOpis = new javax.swing.JTextField();
        jButtonDodajNalaz = new javax.swing.JButton();
        jButtonIzmeniNalaz = new javax.swing.JButton();
        jComboBoxFizijatar = new javax.swing.JComboBox<>();
        jComboBoxPacijent = new javax.swing.JComboBox<>();
        jButtonIzmeniStavku = new javax.swing.JButton();
        jComboBoxSveTerapije = new javax.swing.JComboBox<>();
        jTextFieldCenaTerapije = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonDodajStavku = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStavkaNalaza = new javax.swing.JTable();
        jButtonObrisiStavku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fizijatar:");

        jLabel4.setText("Pacijent:");

        jLabel5.setText("Datum (dd.mm.yyyy.) :");

        jLabel6.setText("Opis:");

        jButtonDodajNalaz.setText("Dodaj nalaz");

        jButtonIzmeniNalaz.setText("Izmeni nalaz");

        jButtonIzmeniStavku.setText("Izmeni stavku");
        jButtonIzmeniStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniStavkuActionPerformed(evt);
            }
        });

        jLabel2.setText("Terapija:");

        jLabel3.setText("Cena:");

        jButtonDodajStavku.setText("Dodaj stavku");

        jTableStavkaNalaza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableStavkaNalaza);

        jButtonObrisiStavku.setText("Obrisi stavku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPacijent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFizijatar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldOpis)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxSveTerapije, 0, 185, Short.MAX_VALUE)
                                            .addComponent(jTextFieldCenaTerapije, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonDodajStavku)
                                        .addGap(33, 33, 33)
                                        .addComponent(jButtonIzmeniStavku))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonIzmeniNalaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonDodajNalaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jComboBoxFizijatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboBoxPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(24, 24, 24)))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSveTerapije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCenaTerapije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDodajStavku)
                            .addComponent(jButtonIzmeniStavku))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonObrisiStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDodajNalaz)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonIzmeniNalaz)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIzmeniStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniStavkuActionPerformed

    }//GEN-LAST:event_jButtonIzmeniStavkuActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajNalaz;
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonIzmeniNalaz;
    private javax.swing.JButton jButtonIzmeniStavku;
    private javax.swing.JButton jButtonObrisiStavku;
    private javax.swing.JComboBox<Fizijatar> jComboBoxFizijatar;
    private javax.swing.JComboBox<Pacijent> jComboBoxPacijent;
    private javax.swing.JComboBox<Terapija> jComboBoxSveTerapije;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStavkaNalaza;
    private javax.swing.JTextField jTextFieldCenaTerapije;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldOpis;
    // End of variables declaration//GEN-END:variables

    public void addActionListenerDodajNalaz(ActionListener actionListener) {
        jButtonDodajNalaz.addActionListener(actionListener);
    }

    

    public void addActionListenerIzmeni(ActionListener actionListener) {
       jButtonIzmeniNalaz.addActionListener(actionListener);
    }

    public void addActionListenerDodajStavku(ActionListener actionListener) {
        jButtonDodajStavku.addActionListener(actionListener);
    }
    
    public void pokreniNit() {
        nit=new DodavanjeStavkeNalazaNit(this);
        nit.start();
    }

    public JTable getjTableStavkaNalaza() {
        return jTableStavkaNalaza;
    }

    public void setjTableStavkaNalaza(JTable jTableStavkaNalaza) {
        this.jTableStavkaNalaza = jTableStavkaNalaza;
    }

    public void addActionListenerIzmeniStavku(ActionListener actionListener) {
        jButtonIzmeniStavku.addActionListener(actionListener);
    }

    public void addWindowListener1(WindowAdapter windowAdapter) {
        this.addWindowListener(windowAdapter);
    }

    public void addActionListenerObrisiStavku(ActionListener actionListener) {
        jButtonObrisiStavku.addActionListener(actionListener);
    }
    
}
