/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ai.klijent.forme;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author milos
 */
public class PrikazNalazaForma extends javax.swing.JFrame {

    /**
     * Creates new form PrikazNalazaForma
     */
    public PrikazNalazaForma() {
        initComponents();
    }

    public JTable getjTableNalaz() {
        return jTableNalaz;
    }

    public void setjTableNalaz(JTable jTableNalaz) {
        this.jTableNalaz = jTableNalaz;
    }

    public JTable getjTableStavkaNalaza() {
        return jTableStavkaNalaza;
    }

    public void setjTableStavkaNalaza(JTable jTableStavkaNalaza) {
        this.jTableStavkaNalaza = jTableStavkaNalaza;
    }

    public JButton getjButtonFiltrirajNalaze() {
        return jButtonFiltrirajNalaze;
    }

    public void setjButtonFiltrirajNalaze(JButton jButtonFiltrirajNalaze) {
        this.jButtonFiltrirajNalaze = jButtonFiltrirajNalaze;
    }

    public JButton getjButtonFiltrirajTerapije() {
        return jButtonFiltrirajTerapije;
    }

    public void setjButtonFiltrirajTerapije(JButton jButtonFiltrirajTerapije) {
        this.jButtonFiltrirajTerapije = jButtonFiltrirajTerapije;
    }

    public JButton getjButtonResetujNalazi() {
        return jButtonResetujNalazi;
    }

    public void setjButtonResetujNalazi(JButton jButtonResetujNalazi) {
        this.jButtonResetujNalazi = jButtonResetujNalazi;
    }

    public JButton getjButtonResetujTerapije() {
        return jButtonResetujTerapije;
    }

    public void setjButtonResetujTerapije(JButton jButtonResetujTerapije) {
        this.jButtonResetujTerapije = jButtonResetujTerapije;
    }

    public JTextField getjTextFieldCenaTerapije() {
        return jTextFieldCenaTerapije;
    }

    public void setjTextFieldCenaTerapije(JTextField jTextFieldCenaTerapije) {
        this.jTextFieldCenaTerapije = jTextFieldCenaTerapije;
    }

    public JTextField getjTextFieldImeFizijatra() {
        return jTextFieldImeFizijatra;
    }

    public void setjTextFieldImeFizijatra(JTextField jTextFieldImeFizijatra) {
        this.jTextFieldImeFizijatra = jTextFieldImeFizijatra;
    }

    public JTextField getjTextFieldImePacijenta() {
        return jTextFieldImePacijenta;
    }

    public void setjTextFieldImePacijenta(JTextField jTextFieldImePacijenta) {
        this.jTextFieldImePacijenta = jTextFieldImePacijenta;
    }

    public JTextField getjTextFieldNazivTerapije() {
        return jTextFieldNazivTerapije;
    }

    public void setjTextFieldNazivTerapije(JTextField jTextFieldNazivTerapije) {
        this.jTextFieldNazivTerapije = jTextFieldNazivTerapije;
    }

    public JTextField getjTextFieldPrezimeFizijatra() {
        return jTextFieldPrezimeFizijatra;
    }

    public void setjTextFieldPrezimeFizijatra(JTextField jTextFieldPrezimeFizijatra) {
        this.jTextFieldPrezimeFizijatra = jTextFieldPrezimeFizijatra;
    }

    public JTextField getjTextFieldPrezimePacijenta() {
        return jTextFieldPrezimePacijenta;
    }

    public void setjTextFieldPrezimePacijenta(JTextField jTextFieldPrezimePacijenta) {
        this.jTextFieldPrezimePacijenta = jTextFieldPrezimePacijenta;
    }

    public JTextField getjTextFieldUkupnaCena() {
        return jTextFieldUkupnaCena;
    }

    public void setjTextFieldUkupnaCena(JTextField jTextFieldUkupnaCena) {
        this.jTextFieldUkupnaCena = jTextFieldUkupnaCena;
    }

  

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNalaz = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStavkaNalaza = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldImeFizijatra = new javax.swing.JTextField();
        jTextFieldPrezimeFizijatra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrezimePacijenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldImePacijenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUkupnaCena = new javax.swing.JTextField();
        jButtonFiltrirajNalaze = new javax.swing.JButton();
        jButtonResetujNalazi = new javax.swing.JButton();
        jTextFieldCenaTerapije = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonFiltrirajTerapije = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNazivTerapije = new javax.swing.JTextField();
        jButtonResetujTerapije = new javax.swing.JButton();
        jButtonObrisiNalaz = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonDodajNalaz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableNalaz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableNalaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNalazMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNalaz);

        jTableStavkaNalaza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableStavkaNalaza);

        jLabel1.setText("Ime fizijatra:");

        jLabel2.setText("Prezime fizijatra:");

        jLabel3.setText("Prezime pacijenta:");

        jLabel4.setText("Ime pacijenta:");

        jLabel5.setText("Ukupna cena:");

        jButtonFiltrirajNalaze.setText("Filtriraj nalaze");

        jButtonResetujNalazi.setText("Resetuj filter za nalaze");

        jLabel6.setText("Cena terapije:");

        jButtonFiltrirajTerapije.setText("Filtriraj stavke nalaza");

        jLabel10.setText("Naziv terapije:");

        jButtonResetujTerapije.setText("Resetuj filter za stavke nalaza");

        jButtonObrisiNalaz.setText("Obrisi nalaz");

        jButtonIzmeni.setText("Izmeni nalaz");

        jButtonDodajNalaz.setText("Dodaj nalaz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPrezimePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonFiltrirajNalaze)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonResetujNalazi)))))
                                .addGap(247, 247, 247))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldImePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPrezimeFizijatra, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldImeFizijatra, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(256, 256, 256)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonObrisiNalaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDodajNalaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCenaTerapije, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonResetujTerapije)
                            .addComponent(jButtonFiltrirajTerapije)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNazivTerapije, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldImeFizijatra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrezimeFizijatra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldImePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldPrezimePacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFiltrirajNalaze)
                            .addComponent(jButtonResetujNalazi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldNazivTerapije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldCenaTerapije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFiltrirajTerapije)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonResetujTerapije)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonDodajNalaz)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonIzmeni)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonObrisiNalaz)
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableNalazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNalazMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableNalazMouseClicked

    /**
     * @param args the command line arguments
     */
    public void addMouseListener(MouseListener mouseListener){
        jTableNalaz.addMouseListener(mouseListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajNalaz;
    private javax.swing.JButton jButtonFiltrirajNalaze;
    private javax.swing.JButton jButtonFiltrirajTerapije;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonObrisiNalaz;
    private javax.swing.JButton jButtonResetujNalazi;
    private javax.swing.JButton jButtonResetujTerapije;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableNalaz;
    private javax.swing.JTable jTableStavkaNalaza;
    private javax.swing.JTextField jTextFieldCenaTerapije;
    private javax.swing.JTextField jTextFieldImeFizijatra;
    private javax.swing.JTextField jTextFieldImePacijenta;
    private javax.swing.JTextField jTextFieldNazivTerapije;
    private javax.swing.JTextField jTextFieldPrezimeFizijatra;
    private javax.swing.JTextField jTextFieldPrezimePacijenta;
    private javax.swing.JTextField jTextFieldUkupnaCena;
    // End of variables declaration//GEN-END:variables

    
    public void addActionListenerFilterNalaza(ActionListener actionListener) {
        jButtonFiltrirajNalaze.addActionListener(actionListener);
    }

    public void addActionListenerResetFilteraNalaza(ActionListener actionListener) {
        jButtonResetujNalazi.addActionListener(actionListener);
    }

    public void addActionListenerResetFilteraTerapija(ActionListener actionListener) {
        jButtonResetujTerapije.addActionListener(actionListener);
    }

    public void addActionListenerFilterTerapija(ActionListener actionListener) {
        jButtonFiltrirajTerapije.addActionListener(actionListener);
    }

    public void addActionListenerObrisiNalaz(ActionListener actionListener) {
        jButtonObrisiNalaz.addActionListener(actionListener);
    }

    

    public void addActionListenerIzmeniNalaz(ActionListener actionListener) {
        jButtonIzmeni.addActionListener(actionListener);
    }

    public void addActionListenerDodajNalaz(ActionListener actionListener) {
        jButtonDodajNalaz.addActionListener(actionListener);
    }

    public void addWindowListener1(WindowAdapter windowAdapter) {
        this.addWindowListener(windowAdapter);
    }
}
